### 1)

In [2]:
# 5 dimensional array with all zeros and ones


import numpy as np

In [17]:
a = np.random.randint(2,size=(5,5)) 
b = np.zeros((1,1,1,5,5),dtype=int)
b[0,0,0,:,:]=a
print(b)

[[[[[1 0 1 1 1]
    [1 0 1 1 1]
    [0 1 0 0 0]
    [1 1 1 1 0]
    [0 1 0 1 1]]]]]


### 2)

In [19]:
x= np.zeros([10],dtype=int)
y= np.ones([10],dtype=int)
z= np.full([10],5,dtype=int)
u= np.vstack((x,y,z))



In [20]:
u

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

### 3)

In [21]:
x=np.arange(10,22).reshape(3,4)
x

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

### 4)

In [28]:
np.diag([0,1,2,3,4,5,6,7,8,9])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

### 5)

In [23]:
y = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
np.flip(y,0)


array([[13, 14, 15, 16],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

### 6)

In [24]:
a = np.array([12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27])
np.flip(a)

array([27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

### 7)

In [32]:
a = np.arange(1,101).reshape(10,10)
b = []
for i in a:
    for s in i:
        if s>30 and s<80 and s%5==0:
            b.append(s)
print(a)

print("\nelements grater than 30,less than 80 and multiple of 5 are:")
print(b)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]

elements grater than 30,less than 80 and multiple of 5 are:
[35, 40, 45, 50, 55, 60, 65, 70, 75]


### 8)

In [49]:
v = np.ones((4,4),dtype=int)
v[1:-1,1:-1]=0


In [50]:
v

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

### 9)

In [55]:
r = int(input("enter a rows: "))
c = int(input("enter a columns: "))
z = np.zeros((r,c),dtype=int)
for i in range(r):
    for j in range(c):
        if (i+j)%2==0:
            z[i,j]=1
print(z)

enter a rows: 10
enter a columns: 10
[[1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]]


### 10)

In [56]:
x = np.array([10,20,30,40])
y = np.array([10,50,20,60])
z = np.intersect1d(x,y)

In [57]:
z

array([10, 20])

### 11)

In [62]:
c1 = np.array([[1,2,3],[4,5,6]])
c2 = c1.reshape(-1)
print("original array")
print(c1)
print("reshaped array",c2)

original array
[[1 2 3]
 [4 5 6]]
reshaped array [1 2 3 4 5 6]


### 12)

In [63]:
a = []
for i in range(0,11):
    a.append(i)
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
